# wrangler.toml
name = "senu"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[dev]
port = 3000

[vars]

[env.preview.vars]


[env.production.vars]

[[r2_buckets]]


[[env.preview.r2_buckets]]

[[env.production.r2_buckets]]


[[kv_namespaces]]


[[env.preview.kv_namespaces]]


[[env.production.kv_namespaces]]


[[kv_namespaces]]


[[env.preview.kv_namespaces]]


[[env.production.kv_namespaces]]

